### ISSUE TITLE
TypeError: Cannot read property 'username' of undefined

### ISSUE THREAD

**Issue by kovan** [LaKing/ep_codepad#10]
I am getting this error and I can't use codepad. It happens after I click the "New Pad" button.
I am using MySQL as backend DB.
What could it be?

`[2016-03-28 23:50:57.851] [ERROR] console - TypeError: Cannot read property 'username' of undefined
    at /var/www/codepad/node_modules/ep_codepad/auth.js:128:92
    at /var/www/codepad/src/node/db/AuthorManager.js:55:5
    at Object.callback (/var/www/codepad/src/node/db/AuthorManager.js:115:7)
    at /var/www/codepad/src/node_modules/ueberdb2/CloneAndAtomicLayer.js:100:17
    at exports.database.get (/var/www/codepad/src/node_modules/ueberdb2/CacheAndBufferLayer.js:144:5)
    at doOperation [as operatorFunction] (/var/www/codepad/src/node_modules/ueberdb2/CloneAndAtomicLayer.js:94:18)
    at iterator (/var/www/codepad/src/node_modules/channels/channels.js:66:17)
    at /var/www/codepad/src/node_modules/ueberdb2/CloneAndAtomicLayer.js:103:7
    at /var/www/codepad/src/node_modules/ueberdb2/CacheAndBufferLayer.js:185:7
    at null.callback (/var/www/codepad/src/node_modules/ueberdb2/postgres_db.js:78:5)
`

**Comment by kovan** [comment]
An error occured
The error was reported with the following id: 'Ouo3v7nnjqmpWNftmwb1'
Also, the browser shows:

Please press and hold Ctrl and press F5 to reload this page, if the problem persists please send this error message to your webmaster:
```
'ErrorId: Ouo3v7nnjqmpWNftmwb1
URL: https://code.onsync.ro/p/roDLsS6vxI
UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36
Uncaught TypeError: Cannot read property 'setChannelState' of null in https://code.onsync.ro/javascripts/lib/ep_etherpad-lite/static/js/pad.js?callback=require.define at line 266'
```

**Comment by LaKing** [comment]
The second error is caused by the first one. 
context.client.request.session.user.username is undefined for you in auth.js

Do you have authentication enabled?

**Comment by kovan** [comment]
How do I know if I have it enabled? I mostly copied and pasted the sample config that is on the GitHub project page to my settings.json.

**Comment by LaKing** [comment]
Did it request an username and a password at first login?

  "requireAuthentication": true,

.. in settings.json?

**Comment by kovan** [comment]
No and no, so no, authentication is disabled.

**Comment by LaKing** [comment]
@kovan It is **STRONGLY** recommended to use authentication and / or authorization.
 ... keep in mind that failing to do so will make evil people possible to gain access on your system.

Fixed.
