### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by skylarmt** [LaKing/ep_codepad#2]
This is what I see in my browser when I try to load a pad:

```
An error occured
The error was reported with the following id: 'aFAfEJG0h6bTkGSuqCCQ'

Please press and hold Ctrl and press F5 to reload this page, if the problem persists please send this error message to your webmaster:
'ErrorId: aFAfEJG0h6bTkGSuqCCQ
URL: http://example.com/p/Schedule
UserAgent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0
TypeError: pad.collabClient is null in http://example.com/javascripts/lib/ep_etherpad-lite/static/js/pad.js?callback=require.define at line 254'
```

Pressing Ctrl-F5 (force-reload) changes nothing.
Running Ubuntu Server 14.04.

**Comment by LaKing** [comment]
Please comment out blocks in ep.json, and let me know what part is causing the issue.

Could you send me your settings.json?

**Comment by skylarmt** [comment]
It stopped doing it after I killed/restarted Etherpad/Ubuntu completely.  You should add a note somewhere for other people that get this problem, as Etherpad can't seem to install it correctly with just a reload.

**Comment by LaKing** [comment]
Ok, .. thanks.
